### ISSUE TITLE
dossier.models.html generation broken?

### ISSUE THREAD

**Issue by dlovell** [dossier/dossier-sphinx#1]
When I go to http://dossier-stack.readthedocs.org/en/latest/dossier.models.html, I see

> System Message: WARNING/2 (/var/build/user_builds/dossierstack/checkouts/latest/dossier.models.rst, line 3)
> 
> autodoc: failed to import module u’dossier.models’; the following exception was raised: Traceback (most recent call last): File “/home/docs/checkouts/readthedocs.org/user_builds/dossier-stack/envs/latest/local/lib/python2.7/site-packages/sphinx/ext/autodoc.py”, line 335, in import_object __import__(self.modname) File 

...

> x86_64.egg/sklearn/datasets/__init__.py”, line 23, in <module> from .twenty_newsgroups import fetch_20newsgroups File “/home/docs/checkouts/readthedocs.org/user_builds/dossier-stack/envs/latest/local/lib/python2.7/site-packages/scikit_learn-0.16.0-py2.7-linux-x86_64.egg/sklearn/datasets/twenty_newsgroups.py”, line 53, in <module> from ..feature_extraction.text import CountVectorizer RuntimeError: sys.path must be a list of directory names

**Comment by BurntSushi** [comment]
Yup, we added some stuff with `nltk` recently and it caused RTD to fall over. Thanks for the reported!

Fixed in 3edeaf8, 549a93e and 2e757b5. (Your link works now.)
